### ISSUE TITLE
New lint rule for detecting missing sample fragments

### ISSUE THREAD

**Issue by savvyintegrations** [microcks/microcks-spectral-ruleset#12]
### Reason/Context

In cases where both a path param and request body are marked as required, it would be great to have a lint rule that detected if one or both are missing fragments to form a complete sample.

### Description

For more info see https://github.com/microcks/microcks/issues/1256

**Comment by lbroudoux** [comment]
I come back to this one, and I think, in fact, that the rule is already in place. We have this one today:

```yaml
  microcks-examples-in-required-parameter:
    description: Required param must have examples
    message: "Required param must have examples"
    formats:
      - oas3
    severity: warn
    given: "$..parameters[?(@.required == true)]"
    then:
      field: examples
      function: truthy
```

that is actually fired by the example resources in that project:

```
49:11  warning  microcks-examples-in-required-parameter        Required param must have examples                                                                                                                                                                         paths./forecast/{region}.get.parameters[1]
```

I just wonder if the severity level shouldn't be upgraded to `error` instead of a simple `warn`? That's maybe what makes it go under the radar... What do you think?
