### ISSUE TITLE
Ability to disable a lint rule for a specific resource

### ISSUE THREAD

**Issue by savvyintegrations** [microcks/microcks-spectral-ruleset#9]
### Reason/Context

Like I can with eslint rules, I'd like to be able to disable a Microcks lint rule for any applicable resource in an OAS doc by specifying, say, `x-microcks-ignore-rules` and setting an array with rule names, e.g, `["microcks-examples-in-request-content"]`.

### Description

I think it's all stated above. This would not be a breaking change.

**Comment by lbroudoux** [comment]
Hi @savvyintegrations,
I had a look at what is possible to do at a Spectral rule level and it seems that the "canonical way" to it is to use [Overrides](https://meta.stoplight.io/docs/spectral/293426e270fac-overrides). 

Instead of having your ignore-list managed at the specification level, it involves managing it within a `.spectral.yaml` file at the project level. Using overrides you can achieve what you want with this syntax if you want to ignore one rule for a specific element of your spec:

```yaml
extends:
  - "https://unpkg.com/@microcks/spectral-ruleset@0.0.4"
overrides:
  - files:
    - "resources/weather-forecast-*.yaml#/paths/~1forecast~1%7Bregion%7D/get"
    rules:
      microcks-operation-extension-valid: "off"
```

I have run some tests and Microcks rules can be ignored that way.
 I find it more elegant than implementing something specific to Microcks. What do you think?
